context("Generate test data")

generateDIAlignRdata <- function(){
  dataPath <- "../../data/testData2/"
  oswMerged <- FALSE
  nameCutPattern <- "(.*)(/)(.*)"
  filenames <- getRunNames(dataPath, oswMerged, nameCutPattern)
  oswFiles_DIAlignR <- getOswFiles(dataPath, filenames, maxFdrQuery = 0.05, analyteFDR = 0.01,
                                   oswMerged, analytes = NULL, runType = "DIA_proteomics")
  refAnalytes <- getAnalytesName(oswFiles_DIAlignR, 1.0, commonAnalytes = TRUE)
  set.seed(1)
  refAnalytes <- sample(refAnalytes, 400)
  refAnalytes <- c(refAnalytes,"KLYAGAILEV_2")
  for (i in seq_along(oswFiles_DIAlignR)){
    keep <- which(oswFiles_DIAlignR[[i]]$transition_group_id %in% refAnalytes)
    keep <- c(keep, sample(which(!oswFiles_DIAlignR[[i]]$transition_group_id %in% refAnalytes), 100))
    oswFiles_DIAlignR[[i]] <- oswFiles_DIAlignR[[i]][keep,]
  }
  oswFiles_DIAlignR[[1]]$filename <- "DIAlignR/testData2/dia_files/191124_PM_BD-ZH12_shbh_10%_DIA_#1_400-650mz_msms41.mzML"
  oswFiles_DIAlignR[[2]]$filename <- "DIAlignR/testData2/dia_files/191124_PM_BD-ZH12_shbh_10%_DIA_#1_400-650mz_msms42.mzML"
  oswFiles_DIAlignR[[3]]$filename <- "DIAlignR/testData2/dia_files/191124_PM_BD-ZH12_shbh_10%_DIA_#1_400-650mz_msms35.mzML"
  save(oswFiles_DIAlignR, file = "oswFiles_DIAlignR.RData")

  analytes <- "KLYAGAILEV_2"
  runs <- c("run0" = "191124_PM_BD-ZH12_shbh_10%_DIA_#1_400-650mz_msms41",
            "run1" = "191124_PM_BD-ZH12_shbh_10%_DIA_#1_400-650mz_msms42",
            "run2" = "191124_PM_BD-ZH12_shbh_10%_DIA_#1_400-650mz_msms35",
            stringsAsFactors=FALSE)
  runs <- c("run0" = "170407_AM_BD-ZH12_Spleen_W_10%_DIA_#1_400-650mz_msms41",
            "run1" = "170407_AM_BD-ZH12_Spleen_W_10%_DIA_#2_400-650mz_msms42",
            "run2" = "170413_AM_BD-ZH12_BoneMarrow_W_10%_DIA_#2_400-650mz_msms35")
  outData <- getXICs4AlignObj(dataPath, runs, oswFiles_DIAlignR, analytes,
                              SgolayFiltOrd = 4, SgolayFiltLen = 5)
  XIC_KLYAGAILEV_2_DIAlignR <- outData
  save(XIC_KLYAGAILEV_2, file = "XIC_KLYAGAILEV_2_DIAlignR.RData")
}

generateDIAlignRchrom <- function(){
  transition_group_id <- c("19051_KLIVTSEGC[160]FK/2", "19052_KLIVTSEGC[160]FK/3",
  "1182_GLPIVNLLK/2", "997_SGEISLSSWEN/2", "13597_VVAGGELFKESVVVNDK/3", "4080_VITMPAGVELTNNNNVITVK/3",
  "4081_VITM[147]PAGVELTNNNNVITVK/3", "12300_IHFLSPVRPFTLTPGDEEESFIQLITPVR/3", "14299_QFNNTDIVLLEDFQK/3",
  "4731_GEANVELTPELAFK/2", "7351_ANAMGIPSLTVTNVPGSTLSR/3", "8704_HEQIDLFDSPNEGTR/2")
  runs <- c("hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW", "hroest_K120809_Strep10%PlasmaBiolRepl2_R04_SW",
            "hroest_K120808_Strep10%PlasmaBiolRepl1_R03_SW")
  con <- DBI::dbConnect(RSQLite::SQLite(), dbname = paste0(runs[1], ".osw"))
  # Generate a query.
  query <- "SELECT PRECURSOR.GROUP_LABEL AS transition_group_id,
  TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID AS transition_id
  FROM PRECURSOR
  INNER JOIN TRANSITION_PRECURSOR_MAPPING ON TRANSITION_PRECURSOR_MAPPING.PRECURSOR_ID = PRECURSOR.ID
  WHERE transition_group_id  = ?"
  IDquery <- DBI::dbSendQuery(con, query)
  DBI::dbBind(IDquery, list(transition_group_id))
  NativeIDS <- DBI::dbFetch(IDquery)
  DBI::dbClearResult(IDquery)
  DBI::dbDisconnect(con)
  write.table(NativeIDS, file = "NativeIDs.csv", sep = ",", row.names= FALSE)
  }

generateMergedOsw <- function(){
  transition_group_id <- c("19051_KLIVTSEGC[160]FK/2", "19052_KLIVTSEGC[160]FK/3",
                           "1182_GLPIVNLLK/2", "997_SGEISLSSWEN/2", "13597_VVAGGELFKESVVVNDK/3", "4080_VITMPAGVELTNNNNVITVK/3",
                           "4081_VITM[147]PAGVELTNNNNVITVK/3", "12300_IHFLSPVRPFTLTPGDEEESFIQLITPVR/3", "14299_QFNNTDIVLLEDFQK/3",
                           "4731_GEANVELTPELAFK/2", "7351_ANAMGIPSLTVTNVPGSTLSR/3", "8704_HEQIDLFDSPNEGTR/2")
  con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "merged.osw")
  query <- "SELECT PRECURSOR.GROUP_LABEL AS transition_group_id FROM PRECURSOR WHERE PRECURSOR.DECOY = 0"
  IDquery <- DBI::dbSendQuery(con, query)
  IDs <- DBI::dbFetch(IDquery)
  DBI::dbClearResult(IDquery)
  set.seed(10)
  IDs <- sample(IDs$transition_group_id, 600)
  transition_group_id <- union(IDs, transition_group_id)

  query <- "SELECT PRECURSOR.GROUP_LABEL AS transition_group_id FROM PRECURSOR WHERE PRECURSOR.DECOY = 1"
  IDquery <- DBI::dbSendQuery(con, query)
  IDs <- DBI::dbFetch(IDquery)
  DBI::dbClearResult(IDquery)
  set.seed(10)
  IDs <- sample(IDs$transition_group_id, 60)
  transition_group_id <- union(IDs, transition_group_id)
  DBI::dbDisconnect(con)

  TEMP <- data.frame("ID" = transition_group_id)
  query1 <- "DELETE FROM PRECURSOR WHERE PRECURSOR.GROUP_LABEL NOT IN
      ( SELECT PRECURSOR.GROUP_LABEL
        FROM PRECURSOR
        INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID)"

  query2 <- "DELETE FROM PRECURSOR_PEPTIDE_MAPPING
  WHERE PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID NOT IN
    (SELECT PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID)"

  query3 <- "DELETE FROM PEPTIDE
  WHERE PEPTIDE.ID NOT IN
    (SELECT PEPTIDE.ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN PEPTIDE ON PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID)"

  query4 <- "DELETE FROM SCORE_PEPTIDE
  WHERE SCORE_PEPTIDE.PEPTIDE_ID NOT IN
    (SELECT SCORE_PEPTIDE.PEPTIDE_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN PEPTIDE ON PEPTIDE.ID = PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID
    INNER JOIN SCORE_PEPTIDE ON SCORE_PEPTIDE.PEPTIDE_ID = PEPTIDE.ID )"

  query5 <- "DELETE FROM FEATURE WHERE FEATURE.ID NOT IN
    (SELECT FEATURE.ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN FEATURE ON PRECURSOR.ID = FEATURE.PRECURSOR_ID )"

  query6 <- "DELETE FROM FEATURE_MS2 WHERE FEATURE_MS2.FEATURE_ID NOT IN
   (SELECT FEATURE_MS2.FEATURE_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN FEATURE_MS2 ON FEATURE_MS2.FEATURE_ID = FEATURE.ID )"

  query7 <- "DELETE FROM SCORE_MS2 WHERE SCORE_MS2.FEATURE_ID NOT IN
    (SELECT SCORE_MS2.FEATURE_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN FEATURE_MS2 ON FEATURE_MS2.FEATURE_ID = FEATURE.ID
    LEFT JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID )"

  query8 <- "DELETE FROM FEATURE_TRANSITION WHERE FEATURE_TRANSITION.FEATURE_ID NOT IN
   (SELECT FEATURE_TRANSITION.FEATURE_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN FEATURE_TRANSITION ON FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID )"

  query9 <- "DELETE FROM TRANSITION_PRECURSOR_MAPPING WHERE TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID NOT IN
    (SELECT TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    LEFT JOIN TRANSITION_PRECURSOR_MAPPING ON TRANSITION_PRECURSOR_MAPPING.PRECURSOR_ID = PRECURSOR.ID )"

  query10 <- "DELETE FROM TRANSITION WHERE TRANSITION.ID NOT IN
    (SELECT TRANSITION.ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    LEFT JOIN TRANSITION_PRECURSOR_MAPPING ON TRANSITION_PRECURSOR_MAPPING.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN TRANSITION ON TRANSITION.ID = TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID )"

  query11 <- "DELETE FROM PEPTIDE_PROTEIN_MAPPING
  WHERE PEPTIDE_PROTEIN_MAPPING.PEPTIDE_ID NOT IN
    (SELECT PEPTIDE_PROTEIN_MAPPING.PEPTIDE_ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
    LEFT JOIN PEPTIDE ON PEPTIDE.ID = PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID
    LEFT JOIN PEPTIDE_PROTEIN_MAPPING ON PEPTIDE_PROTEIN_MAPPING.PEPTIDE_ID = PEPTIDE.ID )"

  query12 <- "DELETE FROM PROTEIN
  WHERE PROTEIN.ID NOT IN
    (SELECT PROTEIN.ID
    FROM PRECURSOR
    INNER JOIN TEMP ON PRECURSOR.GROUP_LABEL = TEMP.ID
    INNER JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
    INNER JOIN PEPTIDE ON PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID
    LEFT JOIN PEPTIDE_PROTEIN_MAPPING ON PEPTIDE_PROTEIN_MAPPING.PEPTIDE_ID = PEPTIDE.ID
    LEFT JOIN PROTEIN ON PROTEIN.ID = PEPTIDE_PROTEIN_MAPPING.PROTEIN_ID )"

  con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "merged.osw")
  DBI::dbBegin(con)
  DBI::dbWriteTable(con, "TEMP", TEMP)
  DBI::dbExecute(con, query1)
  DBI::dbExecute(con, query2)
  DBI::dbExecute(con, query3)
  DBI::dbExecute(con, query4)
  DBI::dbExecute(con, query5)
  DBI::dbExecute(con, query6)
  DBI::dbExecute(con, query7)
  DBI::dbExecute(con, query8)
  DBI::dbExecute(con, query9)
  DBI::dbExecute(con, query10)
  DBI::dbExecute(con, query11)
  DBI::dbExecute(con, query12)
  DBI::dbRemoveTable(con, "TEMP")
  #DBI::dbRollback(con)
  DBI::dbCommit(con)
  DBI::dbExecute(con, "VACUUM")
  DBI::dbDisconnect(con)
}
