# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate similarity matrix for two sequences
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-05
#' @param seq1 (char) A single string
#' @param seq2 (char) A single string
#' @param Match (float) Score for character match
#' @param MisMatch (float) score for character mismatch
#' @param s (matrix) A similarity matrix
#' @return s (matrix) Updated similarity matrix
#' @export
getseqSimMat <- function(seq1, seq2, Match, MisMatch, s) {
    invisible(.Call(`_DIAlignR_getseqSimMat`, seq1, seq2, Match, MisMatch, s))
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
setAffineAlignObj1_S4 <- function(ROW_SIZE, COL_SIZE) {
    .Call(`_DIAlignR_setAffineAlignObj1_S4`, ROW_SIZE, COL_SIZE)
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
setAlignObj_S4 <- function(ROW_SIZE, COL_SIZE) {
    .Call(`_DIAlignR_setAlignObj_S4`, ROW_SIZE, COL_SIZE)
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
doAlignment_S4 <- function(s, signalA_len, signalB_len, gap, OverlapAlignment) {
    .Call(`_DIAlignR_doAlignment_S4`, s, signalA_len, signalB_len, gap, OverlapAlignment)
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
getAlignedInices_NEW <- function(obj) {
    .Call(`_DIAlignR_getAlignedInices_NEW`, obj)
}

#' Initialize a similarity matrix
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
rcpp_s4 <- function(Name) {
    .Call(`_DIAlignR_rcpp_s4`, Name)
}

#' Initialize a similarity matrix
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-05
#' @param initVal (char) Matrix intialization value
#' @param ROW_SIZE (int) Number of rows
#' @param COL_SIZE (int) Number of columns
#' @return s (matrix) a similarity matrix
#' @export
initializeMatrix <- function(initVal, ROW_SIZE, COL_SIZE) {
    .Call(`_DIAlignR_initializeMatrix`, initVal, ROW_SIZE, COL_SIZE)
}

