# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate similarity matrix for two sequences
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-05
#' @param seq1 (char) A single string
#' @param seq2 (char) A single string
#' @param Match (float) Score for character match
#' @param MisMatch (float) score for character mismatch
#' @return s (matrix) Numeric similarity matrix. Rows and columns expresses seq1 and seq2, respectively
#' @examples
#' # Get sequence similarity of two DNA strings
#' Match=10; MisMatch=-2
#' seq1 = "GCAT"; seq2 = "CAGTG"
#' getSeqSimMat(seq1, seq2, Match, MisMatch)
#' @export
getSeqSimMat <- function(seq1, seq2, Match, MisMatch) {
    .Call(`_DIAlignR_getSeqSimMat`, seq1, seq2, Match, MisMatch)
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param ROW_SIZE (int) Number of rows of a matrix
#' @param COL_SIZE (int) Number of columns of a matrix
#' @return affineAlignObj (S4class) A S4class dummy object from C++ class of AffineAlignObj
#' @export
setAffineAlignObj_S4 <- function(ROW_SIZE, COL_SIZE) {
    .Call(`_DIAlignR_setAffineAlignObj_S4`, ROW_SIZE, COL_SIZE)
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
setAlignObj_S4 <- function(ROW_SIZE, COL_SIZE) {
    .Call(`_DIAlignR_setAlignObj_S4`, ROW_SIZE, COL_SIZE)
}

#' Initialize a S4 object AffineAlignObj1
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
doAlignment_S4 <- function(s, signalA_len, signalB_len, gap, OverlapAlignment) {
    .Call(`_DIAlignR_doAlignment_S4`, s, signalA_len, signalB_len, gap, OverlapAlignment)
}

#' Initialize a S4 object AffineAlignObj
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
doAffineAlignment_S4 <- function(s, signalA_len, signalB_len, go, ge, OverlapAlignment) {
    .Call(`_DIAlignR_doAffineAlignment_S4`, s, signalA_len, signalB_len, go, ge, OverlapAlignment)
}

#' Initialize a similarity matrix
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-08
#' @param seq1Len (int) Length of sequence1
#' @param seq2Len (int) Length of sequence2
#' @return affineAlignObj (S4class) An object from C++ class of AffineAlignObj
#' @export
rcpp_s4 <- function(Name) {
    .Call(`_DIAlignR_rcpp_s4`, Name)
}

#' Initialize a similarity matrix
#'
#' @author Shubham Gupta, \email{shubh.gupta@mail.utoronto.ca}
#' ORCID: 0000-0003-3500-8152
#' License: (c) Author (2019) + MIT
#' Date: 2019-03-05
#' @param initVal (char) Matrix intialization value
#' @param ROW_SIZE (int) Number of rows
#' @param COL_SIZE (int) Number of columns
#' @return s (matrix) a similarity matrix
#' @export
initializeMatrix <- function(initVal, ROW_SIZE, COL_SIZE) {
    .Call(`_DIAlignR_initializeMatrix`, initVal, ROW_SIZE, COL_SIZE)
}

